INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'rodolfo66', 'esponjoso23', 'ADMINISTRADOR' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'krustacio', 'cascarudo', 'ADMINISTRADOR' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'frenetico78', 'vasoVacio23', 'ADMINISTRADOR' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'mochila23', 'escolar', 'ADMINISTRADOR' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'hojaenblanco', 'sinescribir', 'ADMINISTRADOR' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'libropastadura', 'bibliotecaDCB', 'EMPLEADO' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'plumapquepinta', 'colorrojo', 'EMPLEADO' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'nuncavende', 'departamentos', 'EMPLEADO' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'infeliz44', 'enlavida:(', 'EMPLEADO' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'robocop22', 'matargatitos', 'EMPLEADO' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'killermaster', 'runlatexunico', 'EMPLEADO' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'sevahacerono', 'carnitasada', 'EMPLEADO' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'yurikoyti', 'perestroika', 'EMPLEADO' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'simsimi', 'inteligenciartifical', 'EMPLEADO' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'yoamoelbueno', 'delmaincra', 'EMPLEADO' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'soyrico', 'noesciertojeje', 'CLIENTE' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'adivinante', 'siemprepierde', 'CLIENTE' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'computadora', 'barata123', 'CLIENTE' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'pantallalcd', '18pulgadas', 'CLIENTE' );
INSERT INTO CUENTA( id_cuenta, usuario, password, tipo_cuenta ) VALUES( DEFAULT, 'amorenelaire', 'foreveralone', 'CLIENTE' );
INSERT INTO ADMINISTRADOR( id_administrador, nombre, apellido_paterno, apellido_materno, id_cuenta ) VALUES( DEFAULT, 'Rodolfo', 'Casares', 'Espinoza' , 1 );
INSERT INTO ADMINISTRADOR( id_administrador, nombre, apellido_paterno, apellido_materno, id_cuenta ) VALUES( DEFAULT, 'Nieto', 'Blanco', NULL, 2 );
INSERT INTO ADMINISTRADOR( id_administrador, nombre, apellido_paterno, apellido_materno, id_cuenta ) VALUES( DEFAULT, 'Andres', 'Obrador', 'Lopes', 3 );
INSERT INTO ADMINISTRADOR( id_administrador, nombre, apellido_paterno, apellido_materno, id_cuenta ) VALUES( DEFAULT, 'Elena', 'Sincope', NULL, 4 );
INSERT INTO ADMINISTRADOR( id_administrador, nombre, apellido_paterno, apellido_materno, id_cuenta ) VALUES( DEFAULT, 'Millie', 'Rosalina', 'Servadillo', 5 );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'MEXICO', 'ROSALES', 'PEDRO SOLA', '23' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'CIUDAD JUAREZ', 'ARBOLEADA', 'AGUACALIENTE', '19' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'SALTILLO', 'CLEOPATRA', 'RICARDO FLORES MAGON', '23' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'CHIMALHUACAN', 'CENTRO', 'MOCTEZUMA', '1002' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'GUADALUPE', 'SANTA URSULA', 'FRESNO', '10' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'REYNOSA', 'TABACO', 'MIRADOR', '60' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'TORREON', 'MELCHOR OCAMPO', 'CARMELITA', '22' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'MORELIA', 'PINOTEPA', 'GONZALES', '67' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'TOLUCA DE LERDO', 'SANTA MARIA', 'NUMERO 33', '100' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'GENERAL ESCOBEDO', 'MIRADOR', 'CACAHUATE', '83' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'VILLAHERMOSA', 'OLIMPO', 'SINALOA', '1' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'CELAYA', 'AULLIDOS DEL NORTE', 'AMAPOLA', '55' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'CUERNAVACA', 'PETROLEO', 'VICTORIA', '66' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'CANCUN', 'HEROICA', 'SAN JOSE MILPALTA', '11' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'TEPIC', 'DOLARES MEXICANOS', 'ELOTE CON CHILITO', '15' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'URUAPAN', 'LOS MOCHIS', 'RESPIRO', '90' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'MEXICALI', 'TENEYUCAN', 'CEREZOS', '44' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'SALTILLO', 'CHINA', 'MAGNOLIAS', '4' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'ZAPOPAN', 'LOS GONZALES', 'HUMAREDA', '23' );
INSERT INTO DIRECCION( id_direccion, ciudad, colonia, calle, numero ) VALUES( DEFAULT, 'TIJUANA', 'PRIMAVERA', 'ROCA CALIENTE', '39' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 1, '0445529167777' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 2, '0445567891011' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 3, '0445541516171' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 4, '0445502122232' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 5, '0445562728292' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 6, '0445523334353' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 7, '0445579695942' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 8, '0445557974700' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 9, '0445535752588' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 10, '0445530405064' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 11, '0445553565255' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 12, '0445589808687' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 13, '0445576757473' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 14, '0445545464744' );
INSERT INTO TELEFONO( id_telefono, id_direccion, telefono ) VALUES( DEFAULT, 15, '0445590929345' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'ALPHA' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'BRAVO' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'CHARLIE' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'DELTA' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'ECHO' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'FOXTROT' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'GOLF' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'HOTEL' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'INDIA' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'JULIET' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'KILO' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'LIMA' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'MIKE' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'NOVEMBER' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'OSCAR' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'PAPA' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'QUEBEC' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'ROMEO' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'SIERRA' );
INSERT INTO ZONA( id_zona, nombre_zona ) VALUES( DEFAULT, 'TANGO' );
INSERT INTO AGENCIA( id_agencia, fax, id_direccion, id_titular, id_zona ) VALUES( DEFAULT, '4245787', 1, 1, 1  );
INSERT INTO AGENCIA( id_agencia, fax, id_direccion, id_titular, id_zona ) VALUES( DEFAULT, '424534434', 2, 2, 2  );
INSERT INTO AGENCIA( id_agencia, fax, id_direccion, id_titular, id_zona ) VALUES( DEFAULT, '4535345234', 3, 3, 3  );
INSERT INTO AGENCIA( id_agencia, fax, id_direccion, id_titular, id_zona ) VALUES( DEFAULT, '980193472', 4, 4, 4  );
INSERT INTO AGENCIA( id_agencia, fax, id_direccion, id_titular, id_zona ) VALUES( DEFAULT, '999456932', 5, 5, 5  );
INSERT INTO AGENCIA( id_agencia, fax, id_direccion, id_titular, id_zona ) VALUES( DEFAULT, '024234399', 6, 6, 6  );
INSERT INTO AGENCIA( id_agencia, fax, id_direccion, id_titular, id_zona ) VALUES( DEFAULT, '092349832', 7, 7, 7  );
INSERT INTO AGENCIA( id_agencia, fax, id_direccion, id_titular, id_zona ) VALUES( DEFAULT, '678593744', 8, 8, 8  );
INSERT INTO AGENCIA( id_agencia, fax, id_direccion, id_titular, id_zona ) VALUES( DEFAULT, '087468392', 9, 9, 9  );
INSERT INTO AGENCIA( id_agencia, fax, id_direccion, id_titular, id_zona ) VALUES( DEFAULT, '093409032', 10, 10, 10 );
INSERT INTO EMPLEADO( id_empleado, id_agencia, nombre, apellido_paterno, apellido_materno, tipo_empleado, id_cuenta ) VALUES( DEFAULT, 1, 'Jesus', 'Brumoso', NULL, 'TITULAR', 6 );
INSERT INTO EMPLEADO( id_empleado, id_agencia, nombre, apellido_paterno, apellido_materno, tipo_empleado, id_cuenta ) VALUES( DEFAULT, 2, 'Muriel', 'Coraje', NULL, 'TITULAR', 7 );
INSERT INTO EMPLEADO( id_empleado, id_agencia, nombre, apellido_paterno, apellido_materno, tipo_empleado, id_cuenta ) VALUES( DEFAULT, 3, 'Misa', 'Lawliet', NULL, 'TITULAR', 8 );
INSERT INTO EMPLEADO( id_empleado, id_agencia, nombre, apellido_paterno, apellido_materno, tipo_empleado, id_cuenta ) VALUES( DEFAULT, 4, 'Veronica', 'Amane', NULL, 'TITULAR', 9 );
INSERT INTO EMPLEADO( id_empleado, id_agencia, nombre, apellido_paterno, apellido_materno, tipo_empleado, id_cuenta ) VALUES( DEFAULT, 5, 'Cynthya', 'Garcia', 'Morales', 'TITULAR', 10 );
INSERT INTO EMPLEADO( id_empleado, id_agencia, nombre, apellido_paterno, apellido_materno, tipo_empleado, id_cuenta ) VALUES( DEFAULT, 6, 'Uriel', 'Balderas', 'Garcia', 'VENDEDOR', 11 );
INSERT INTO EMPLEADO( id_empleado, id_agencia, nombre, apellido_paterno, apellido_materno, tipo_empleado, id_cuenta ) VALUES( DEFAULT, 7, 'Vicente', 'Fernandez', 'Fernandez', 'VENDEDOR', 12 );
INSERT INTO EMPLEADO( id_empleado, id_agencia, nombre, apellido_paterno, apellido_materno, tipo_empleado, id_cuenta ) VALUES( DEFAULT, 8, 'Vanessa', 'Verde', 'Ayala', 'VENDEDOR', 13 );
INSERT INTO EMPLEADO( id_empleado, id_agencia, nombre, apellido_paterno, apellido_materno, tipo_empleado, id_cuenta ) VALUES( DEFAULT, 9, 'Patricia', 'Navarro', 'Cervantes', 'VENDEDOR', 14 );
INSERT INTO EMPLEADO( id_empleado, id_agencia, nombre, apellido_paterno, apellido_materno, tipo_empleado, id_cuenta ) VALUES( DEFAULT, 10, 'Rosa', 'Gutierrez', 'Valencia', 'VENDEDOR', 15 );
INSERT INTO TITULAR( id_titular, id_empleado ) VALUES( DEFAULT, 1 );
INSERT INTO TITULAR( id_titular, id_empleado ) VALUES( DEFAULT, 2 );
INSERT INTO TITULAR( id_titular, id_empleado ) VALUES( DEFAULT, 3 );
INSERT INTO TITULAR( id_titular, id_empleado ) VALUES( DEFAULT, 4 );
INSERT INTO TITULAR( id_titular, id_empleado ) VALUES( DEFAULT, 5 );
INSERT INTO TITULAR( id_titular, id_empleado ) VALUES( DEFAULT, 6 );
INSERT INTO TITULAR( id_titular, id_empleado ) VALUES( DEFAULT, 7 );
INSERT INTO TITULAR( id_titular, id_empleado ) VALUES( DEFAULT, 8 );
INSERT INTO TITULAR( id_titular, id_empleado ) VALUES( DEFAULT, 9 );
INSERT INTO TITULAR( id_titular, id_empleado ) VALUES( DEFAULT, 10 );
INSERT INTO VENDEDOR( id_vendedor, id_empleado ) VALUES( DEFAULT, 6 );
INSERT INTO VENDEDOR( id_vendedor, id_empleado ) VALUES( DEFAULT, 7 );
INSERT INTO VENDEDOR( id_vendedor, id_empleado ) VALUES( DEFAULT, 8 );
INSERT INTO VENDEDOR( id_vendedor, id_empleado ) VALUES( DEFAULT, 9 );
INSERT INTO VENDEDOR( id_vendedor, id_empleado ) VALUES( DEFAULT, 10 );
INSERT INTO CLIENTE( id_cliente, id_vendedor, nombre, apellido_paterno, apellido_materno, correo, id_cuenta, id_direccion ) VALUES( DEFAULT, 1, 'Luis', 'Galaviz', NULL, 'floresdeabril@gmail.com', 11, 11 );
INSERT INTO CLIENTE( id_cliente, id_vendedor, nombre, apellido_paterno, apellido_materno, correo, id_cuenta, id_direccion ) VALUES( DEFAULT, 2, 'Joger', 'Torres', 'Moniac', 'corazonbandido@gmail.com', 12, 12 );
INSERT INTO CLIENTE( id_cliente, id_vendedor, nombre, apellido_paterno, apellido_materno, correo, id_cuenta, id_direccion ) VALUES( DEFAULT, 3, 'Francisco', 'Jemes', 'Valencia', 'floresdeabril@gmail.com', 13, 13 );
INSERT INTO CLIENTE( id_cliente, id_vendedor, nombre, apellido_paterno, apellido_materno, correo, id_cuenta, id_direccion ) VALUES( DEFAULT, 4, 'Josue', 'Brincos', NULL, 'pollorostizado@gmail.com', 14, 14 );
INSERT INTO CLIENTE( id_cliente, id_vendedor, nombre, apellido_paterno, apellido_materno, correo, id_cuenta, id_direccion ) VALUES( DEFAULT, 5, 'Fernando', 'Gonzales', 'Flores', 'zapatorojo@gmail.com', 15, 15 );
INSERT INTO INMUEBLE( id_inmueble, id_zona, id_cliente, propietario, tipo_renta_venta, tipo_local_piso ) VALUES( DEFAULT, 11, NULL, 'Checo Perez', 'RENTA', 'LOCAL' );
INSERT INTO INMUEBLE( id_inmueble, id_zona, id_cliente, propietario, tipo_renta_venta, tipo_local_piso ) VALUES( DEFAULT, 12, NULL, 'Julion Alvarez', 'RENTA', 'PISO' );
INSERT INTO INMUEBLE( id_inmueble, id_zona, id_cliente, propietario, tipo_renta_venta, tipo_local_piso ) VALUES( DEFAULT, 13, NULL, 'Paquita del Barrio', 'VENTA', 'LOCAL' );
INSERT INTO INMUEBLE( id_inmueble, id_zona, id_cliente, propietario, tipo_renta_venta, tipo_local_piso ) VALUES( DEFAULT, 14, NULL, 'Frencisco Ceballos', 'VENTA', 'PISO' );
INSERT INTO INMUEBLE( id_inmueble, id_zona, id_cliente, propietario, tipo_renta_venta, tipo_local_piso ) VALUES( DEFAULT, 15, NULL, 'Pedro Sola', 'RENTA', 'LOCAL' );
INSERT INTO VENTA( id_venta, id_inmueble, precio_venta, hipotecado ) VALUES( DEFAULT, 3 , 1200000, 'NO' );
INSERT INTO VENTA( id_venta, id_inmueble, precio_venta, hipotecado ) VALUES( DEFAULT, 4 , 900000, 'NO' );
INSERT INTO ALQUILER( id_alquiler, id_inmueble, precio_alquiler, fianza ) VALUES( DEFAULT, 1, 5000, 2500 );
INSERT INTO ALQUILER( id_alquiler, id_inmueble, precio_alquiler, fianza ) VALUES( DEFAULT, 2 , 6000, 3000 );
INSERT INTO ALQUILER( id_alquiler, id_inmueble, precio_alquiler, fianza ) VALUES( DEFAULT, 5 , 4000, 1500 );
INSERT INTO LOCAL( id_local, id_inmueble, licencia ) VALUES( DEFAULT, 1, 1 );
INSERT INTO LOCAL( id_local, id_inmueble, licencia ) VALUES( DEFAULT, 3, 1 );
INSERT INTO LOCAL( id_local, id_inmueble, licencia ) VALUES( DEFAULT, 5, 1 );
INSERT INTO PISO( id_piso, id_inmueble, num_habitaciones, num_banios, tipo_ambiente, tipo_gas ) VALUES( DEFAULT, 2, 2, 2, 'INTERIOR', 'CIUDAD' );
INSERT INTO PISO( id_piso, id_inmueble, num_habitaciones, num_banios, tipo_ambiente, tipo_gas ) VALUES( DEFAULT, 4, 2, 1, 'EXTERIOR', 'BUTANO' );